general.import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "K"
mods = "Command|Super"

[[keyboard.bindings]]
key = "Up"
mods = "Control"
chars = "\u001b[1;5A"

[[keyboard.bindings]]
key = "Down"
mods = "Control"
chars = "\u001b[1;5B"

[[keyboard.bindings]]
key = "Left"
mods = "Control"
chars = "\u001b[1;5D"

[[keyboard.bindings]]
key = "Right"
mods = "Control"
chars = "\u001b[1;5C"

[window]
opacity = 0.85
blur = true
decorations = "Buttonless"

[window.padding]
x = 0
y = 0

# [colors.primary]
# foreground = "#d8d8d8"
# background = "#181818"
# dim_foreground = "#828482"

# [colors.normal]
# black = "#181818"
# red = "#ac4242"
# green = "#90a959"
# yellow = "#f4bf75"
# blue = "#6a9fb5"
# magenta = "#aa759f"
# cyan = "#75b5aa"
# white = "#d8d8d8"

# [colors.bright]
# black = "#6b6b6b"
# red = "#c55555"
# green = "#aac474"
# yellow = "#feca88"
# blue = "#82b8c8"
# magenta = "#c28cb8"
# cyan = "#93d3c3"
# white = "#f8f8f8"

[font]
size = 23

[font.normal]
family = "FiraCode Nerd Font Mono"

[font.offset]
x = 0
y = 2

[keyboard]
