#!/bin/sh
if [ -z "${BASH_VERSION:-}" ] || shopt -oq posix; then
  exec /bin/bash "$0" "$@"
fi

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

source "$CONFIG_DIR/plugins/colors.sh"
PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=40 blur_radius=30 color="$BAR_COLOR"

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="FiraCode Nerd Font:Bold:17.0"
  label.font="FiraCode Nerd Font:Bold:14.0"
  icon.color="$ACCENT_COLOR"
  label.color="$ACCENT_COLOR"
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Aerospace integration #####
sketchybar --add event aerospace_workspace_change

source "$PLUGIN_DIR/aerospace_workspace_icons.sh"
focused_workspace="$(aerospace list-workspaces --focused)"

for sid in $(aerospace list-workspaces --all); do
  keep_visible_when_empty=false
  if [[ "$sid" == "$focused_workspace" ]]; then
    keep_visible_when_empty=true
  fi

  sketchybar --add item space."$sid" left \
    --subscribe space."$sid" aerospace_workspace_change \
    --set space."$sid" \
    padding_left=0 \
    padding_right=0 \
    drawing="off" \
    background.drawing=off \
    icon.drawing=off \
    label.drawing=off \
    click_script="aerospace workspace $sid"

  create_workspace_icon_items "$sid"
  create_workspace_group "$sid"
  sketchybar --set space."$sid" script="$CONFIG_DIR/plugins/aerospace.sh $sid"
  sketchybar --set space."$sid".group \
    background.color="$ITEM_BG_COLOR" \
    background.corner_radius=5 \
    background.drawing=on \
    background.border_color="$INACTIVE_BORDER_COLOR" \
    background.border_width=1 \
    background.height=25
  render_workspace_items "$sid" "$(aerospace list-windows --workspace "$sid" | extract_workspace_apps_from_windows)" "$keep_visible_when_empty"
  NAME="space.$sid" FOCUSED_WORKSPACE="$focused_workspace" "$CONFIG_DIR/plugins/aerospace.sh" "$sid"

done

sketchybar --add item space_separator left \
  --set space_separator icon="" \
  icon.padding_left=4 \
  label.drawing=off \
  background.drawing=off \
  script="$PLUGIN_DIR/aerospace_workspace_change.sh" \
  --subscribe space_separator aerospace_workspace_change

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add item front_app left \
           --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

right_separator_style=(
  icon=│
  label.drawing=off
  icon.color=0x66ffffff
  icon.padding_left=6
  icon.padding_right=6
  background.drawing=off
)

##### Adding Right Items #####
sketchybar --add item clock right \
           --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
           --add item right_separator.system right \
           --set right_separator.system "${right_separator_style[@]}" \
           --add item right_separator.ai right \
           --set right_separator.ai "${right_separator_style[@]}" drawing=off \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change \
           --add item cpu right \
           --set cpu update_freq=10 icon="" script="$PLUGIN_DIR/cpu.sh" \
           --add item ram right \
           --set ram update_freq=120 icon="󰍛" script="$PLUGIN_DIR/ram.sh"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update

##### AI Usage #####
sketchybar --add item ai_usage.refresh right \
           --set ai_usage.refresh \
           drawing=off \
           update_freq=60 \
           script="$PLUGIN_DIR/ai_usage_refresh.sh"

"$PLUGIN_DIR/ai_usage_refresh.sh" >/dev/null 2>&1 &
