[settings.age]
strict = false

[tools]
"aqua:aws/aws-cli" = "2.36.31"

[bootstrap.packages]
"brew-cask:discord" = "latest"
"brew-cask:anki" = "latest"
"brew-cask:moonlight" = "latest"
"brew-cask:google-chrome" = "latest"
"brew-cask:slack" = "latest"
"brew-cask:zoom" = "latest"
"brew-cask:prusaslicer" = "latest"
"brew-cask:rar" = "latest"
"mas:937984704" = "latest"
"mas:1474276998" = "latest"

[bootstrap.user]
login_shell = "/opt/homebrew/bin/fish"

[dotfiles]
"~/.config/fish/conf.d/10-mise-profile.fish" = "dotfiles/personal/mise-profile.fish"
"~/.gitconfig" = "dotfiles/personal/gitconfig"
"~/.pi/agent/settings.json" = "dotfiles/personal/pi/agent/settings.json"
"~/.pi/agent/mcp.json" = "dotfiles/personal/pi/agent/mcp.json"
"~/.pi/agent/models.json" = "dotfiles/personal/pi/agent/models.json"
"~/.pi/agent/extensions/pi-openai-fast.json" = "dotfiles/personal/pi/agent/extensions/pi-openai-fast.json"
"~/.pi/workflows/model-tiers.json" = "dotfiles/personal/pi/workflows/model-tiers.json"
"~/.agents" = "dotfiles/personal/agents"

[env]
CONTEXT7_API_KEY = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0NlhFYTRGOFE4cHZIRDFERC9XQzN5QkxyNm1rNkUyTHQ2dUczbUdiNHdJCjl2My9WWEthVW9hOFIrazBKemtnWkRGV2M4eUxCdVBhWTl1NllnREtxcE0KLT4gJTdnSFMtZ3JlYXNlIFNOTCAlbHxCK3ljIFk+fUE/Cjh5bWhveW9EbjJuMzJ0NXZMYm9wLzFBZHhveURwNUx5amUzRW5ZL1dMaVpLdXlzU1F6Wkh1L2hPYzNJUE9HSzQKUDNNVFBHY0VYUGhLSlR4VFN3Ci0tLSBXU3k4RlFNR2RseHYxQ3ZUTHlEYkVSRk1nc21hUG9WMCt2djlKMFFjeHMwCgLdme3GEdREgXsKCQw0eLIuq8RpVCUd/36sS4VQQ/s+X5sp+XR7sDLSXs698RLRS0PedQD3E1u4eVxOsJ53OlAu550bxHsb/CqiFA" }
BRAVE_SEARCH_API_KEY = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzY3Rxa0VuV1NEZ1Y1MlZRTE84WFVFTFNFYTk1bFlxZmVHS25wbEhNTmpNCnZobmxlSm5sMFVucFJVT2NzTUo0SmZpVisvRjdUYlY4N1pocVFGYisvM0UKLT4gVS1ncmVhc2UgTFk9biAkLjR4Y09dCjdRCi0tLSBLbVFYSXl6WEZCNC8rdjkzTjdWS0tmeGMrRmdRMzBhRXprdWVUU05COE9JCjHv6m3RFqbVyvpXw0/txHp4qYJtEzH+05zXgrkbV8U6P07pzwMeoti/N8iema1KXL9d4S0zKEPawr2Q+ebDuQ" }
YNAB_API_KEY = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORlZPS3ZPRDIvVUNXdGdRZDUrRDg1eGFnLzh0V0VDMW45TUZoN3RVdlNrCjRtNkVlSmRYMEx2ZFViQnNQMEpTN21ZSlR3TmpydFNNcDRXSWV5dHpIT2MKLT4gST93LWdyZWFzZSA7QjQxWyB3XFZoYkJoRyB4JS0kVmhSQgp0bmhYYkEKLS0tIEdRRzZ0ZjZSallJaTVrVU1rVkNaYUJFc0NzbGwyUEQ5VGtpRWhqOFU1L1kKJsrgYEOlvU3AiZz+l7u7jWtDJXN17+IqzPQ3dvnmZR5MNBwFcrVfZr1LezaRh6XzJ4m8+vo8upisVWUeUTM8joAV3LFUf3Q//swa" }
