#!/usr/bin/env node

import { spawnSync } from "node:child_process";

const paneId = process.argv[2];
if (!paneId || !/^%\d+$/.test(paneId)) {
	process.stdout.write("No live Pi pane selected.\n");
	process.exit(0);
}

const result = spawnSync(
	"tmux",
	["capture-pane", "-p", "-e", "-t", paneId, "-S", "-200"],
	{
		encoding: "utf8",
		maxBuffer: 512 * 1024,
	},
);

if (result.status !== 0) {
	process.stdout.write("This Pi pane is no longer available.\n");
	process.exit(0);
}

const safeOutput = result.stdout
	.slice(-256 * 1024)
	.replace(/\u001b\][\s\S]*?(?:\u0007|\u001b\\)/g, "")
	.replace(/\u001b[PX^_][\s\S]*?\u001b\\/g, "")
	.replace(/\u001b\[[0-?]*[ -/]*[@-~]/g, (sequence) =>
		sequence.endsWith("m") ? sequence : "",
	)
	.replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001a\u001c-\u001f\u007f-\u009f]/g, "");

process.stdout.write(safeOutput || "No pane output yet.\n");
